# Generated by Django 6.0.2 on 2026-02-26 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_user_bio_user_education_user_experience_user_resume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cv_achievements',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='cv_certificates',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='cv_links',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='cv_projects',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='cv_training',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
